[package]
name = "desklink-linux"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
desklink-protocol = { path = "../protocol" }
desklink-config = { path = "../config" }
desklink-topology = { path = "../topology" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
evdev = "0.12"
